import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { UserConfig, getCheapProvider } from './providers';
import { COMPANION_DIR } from './constants';

export interface NotebookPrepEvents {
  /**
   * Fires when a notebook summary becomes available — either loaded from
   * the `.companion/summaries/` cache or freshly generated by the cheap
   * LLM provider. Caller typically uses this to trigger an intro initiative.
   */
  onSummaryReady(summary: string): void;

  /**
   * Fires when we need to signal the UI that we're generating a summary
   * (which can take a few seconds on the cheap provider). 'preparing' is
   * posted at generation start, 'idle' when done or errored out.
   */
  onStatus(state: 'preparing' | 'idle'): void;
}

interface TodoMarker {
  text: string;
  lineNumber: number; // 1-based within the code cell
}

function sourceFromCell(cell: any): string {
  return Array.isArray(cell.source) ? cell.source.join('') : (cell.source || '');
}

function extractTodos(source: string): TodoMarker[] {
  const todos: TodoMarker[] = [];
  const lines = source.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(/TODO:\s*(.*?)\s*$/);
    if (match) {
      const text = match[1].trim();
      if (text) { todos.push({ text, lineNumber: i + 1 }); }
    }
  }
  return todos;
}

function buildSolutionExcerpt(
  filename: string,
  cellIndex: number,
  todo: TodoMarker,
  studentSource: string,
  solutionSource: string,
): string {
  const maxChars = 4_000;
  const header = [
    `Reference solution for ${filename}, cell ${cellIndex + 1}.`,
    `Matched TODO: ${todo.text}`,
    '',
  ].join('\n');

  if (solutionSource.length <= maxChars) {
    return header + solutionSource;
  }

  const studentLineCount = Math.max(1, studentSource.split('\n').length);
  const solutionLines = solutionSource.split('\n');
  const approxSolutionLine = Math.max(
    1,
    Math.min(
      solutionLines.length,
      Math.round((todo.lineNumber / studentLineCount) * solutionLines.length),
    ),
  );

  let start = Math.max(0, approxSolutionLine - 35);
  let end = Math.min(solutionLines.length, approxSolutionLine + 65);
  let excerpt = solutionLines.slice(start, end).join('\n');

  while (excerpt.length > maxChars && end - start > 20) {
    if (approxSolutionLine - start > end - approxSolutionLine) {
      start++;
    } else {
      end--;
    }
    excerpt = solutionLines.slice(start, end).join('\n');
  }

  return [
    header.trimEnd(),
    `Showing solution excerpt around approximate line ${approxSolutionLine} of ${solutionLines.length}.`,
    `Lines ${start + 1}-${end}:`,
    '```python',
    excerpt,
    '```',
  ].join('\n');
}

/**
 * Owns everything related to "what does Zee know about this specific
 * notebook": the LLM-generated summary (cached to disk after first use)
 * and the per-TODO solution cells (loaded from the sibling `solution/`
 * folder and used to give contextual hints).
 *
 * Single-flight: if `prepare` is called for a new notebook while another
 * is still generating, the in-flight result is discarded. Safe to call
 * repeatedly from context-update handlers.
 */
export class NotebookPrep {
  private summary: string | null = null;
  private solutions: Map<string, string> = new Map();
  private solutionsByCellTodo: Map<string, string> = new Map();
  private preparing: string | null = null;
  // Which notebook's state we currently hold — used so re-calling prepare()
  // on a notebook we've already loaded is idempotent (no duplicate summary
  // events, no redundant re-reads).
  private loadedFor: string | null = null;

  constructor(
    private getConfig: () => UserConfig,
    private events: NotebookPrepEvents,
  ) {}

  getSummary(): string | null {
    return this.summary;
  }

  getSolution(todoText: string, cellIndex?: number): string | undefined {
    if (cellIndex !== undefined) {
      const cellScoped = this.solutionsByCellTodo.get(this.solutionKey(cellIndex, todoText));
      if (cellScoped) { return cellScoped; }
    }
    return this.solutions.get(todoText);
  }

  /**
   * Reset per-notebook state. Called when the user clears the transcript
   * or switches away from the current notebook.
   */
  clear(): void {
    this.summary = null;
    this.solutions.clear();
    this.solutionsByCellTodo.clear();
    this.preparing = null;
    this.loadedFor = null;
  }

  /**
   * Fire-and-forget: loads solution cells synchronously, then loads or
   * generates the summary. On success, events.onSummaryReady fires with
   * the final summary text. Safe to call for a notebook that's already
   * being prepared (it's a no-op).
   */
  prepare(filename: string, notebookUri: vscode.Uri): void {
    if (this.preparing === filename) { return; }
    if (this.loadedFor === filename) { return; }  // already prepared; idempotent
    this.preparing = filename;
    this.prepareAsync(filename, notebookUri).catch(() => {
      // Errors surface via onStatus('idle'); swallow here so an unhandled
      // rejection doesn't kill the extension host.
    });
  }

  private async prepareAsync(filename: string, notebookUri: vscode.Uri): Promise<void> {
    try {
      this.loadSolutionCells(filename, notebookUri);

      const cachePath = this.getSummaryCachePath(filename);
      if (fs.existsSync(cachePath)) {
        if (this.preparing === filename) {
          this.summary = fs.readFileSync(cachePath, 'utf-8');
          this.loadedFor = filename;
          this.events.onSummaryReady(this.summary);
        }
        return;
      }

      // Cache miss — generate. onStatus('preparing') lets the UI show a
      // spinner while the cheap provider runs.
      this.events.onStatus('preparing');
      const summary = await this.generateSummary(filename, notebookUri);
      if (this.preparing !== filename) { return; }  // user switched notebooks

      if (summary) {
        this.summary = summary;
        this.loadedFor = filename;
        const cacheDir = this.getSummaryCacheDir();
        fs.mkdirSync(cacheDir, { recursive: true });
        fs.writeFileSync(cachePath, summary, 'utf-8');
        this.events.onSummaryReady(summary);
      }
      this.events.onStatus('idle');
    } catch {
      if (this.preparing === filename) { this.events.onStatus('idle'); }
    } finally {
      if (this.preparing === filename) { this.preparing = null; }
    }
  }

  /**
   * Delete the on-disk summary cache for this notebook. Called when the
   * user explicitly clears their transcript so a fresh session re-prepares
   * from scratch.
   */
  deleteCache(filename: string): void {
    try {
      const cachePath = this.getSummaryCachePath(filename);
      if (fs.existsSync(cachePath)) { fs.unlinkSync(cachePath); }
    } catch { /* ignore */ }
  }

  // ── Private: cache paths ────────────────────────────────────────────

  private getSummaryCacheDir(): string {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    const root = workspaceFolders?.[0]?.uri.fsPath ?? '';
    return path.join(root, COMPANION_DIR, 'summaries');
  }

  private getSummaryCachePath(filename: string): string {
    const base = filename.replace(/\.ipynb$/, '');
    return path.join(this.getSummaryCacheDir(), `${base}.txt`);
  }

  // ── Private: solution loading ───────────────────────────────────────

  private loadSolutionCells(filename: string, notebookUri: vscode.Uri): void {
    this.solutions.clear();
    this.solutionsByCellTodo.clear();

    try {
      const notebookDir = path.dirname(notebookUri.fsPath);
      const solutionPath = path.join(notebookDir, 'solution', filename);
      if (!fs.existsSync(solutionPath)) { return; }

      const studentRaw = JSON.parse(fs.readFileSync(notebookUri.fsPath, 'utf-8'));
      const raw = JSON.parse(fs.readFileSync(solutionPath, 'utf-8'));
      const studentCells = studentRaw.cells || [];
      const cells = raw.cells || [];

      // Backward-compatible path for tests / older solution notebooks that
      // still carried TODO markers directly in the solved code.
      cells.forEach((cell: any, index: number) => {
        if (cell.cell_type !== 'code') { return; }
        const source = sourceFromCell(cell);
        for (const todo of extractTodos(source)) {
          this.rememberSolution(todo.text, index, source);
        }
      });

      // Real course path: root notebooks contain TODO comments; solution
      // notebooks contain the same cells solved, without TODO markers. Map
      // each root TODO to the same-index solved cell, with a bounded excerpt
      // around the corresponding line when the solved cell is large.
      studentCells.forEach((studentCell: any, index: number) => {
        if (studentCell.cell_type !== 'code') { return; }
        const solutionCell = cells[index];
        if (!solutionCell || solutionCell.cell_type !== 'code') { return; }

        const studentSource = sourceFromCell(studentCell);
        const solutionSource = sourceFromCell(solutionCell);
        if (!solutionSource.trim()) { return; }

        const todos = extractTodos(studentSource);
        for (const todo of todos) {
          const excerpt = buildSolutionExcerpt(
            filename,
            index,
            todo,
            studentSource,
            solutionSource,
          );
          this.rememberSolution(todo.text, index, excerpt);
        }
      });
    } catch { /* solution not available — that's fine */ }
  }

  private rememberSolution(todoText: string, cellIndex: number, solution: string): void {
    const trimmed = todoText.trim();
    if (!trimmed) { return; }
    this.solutionsByCellTodo.set(this.solutionKey(cellIndex, trimmed), solution);
    if (!this.solutions.has(trimmed)) {
      this.solutions.set(trimmed, solution);
    }
  }

  private solutionKey(cellIndex: number, todoText: string): string {
    return `${cellIndex}:${todoText.trim()}`;
  }

  // ── Private: summary generation via cheap LLM ──────────────────────

  private async generateSummary(filename: string, notebookUri: vscode.Uri): Promise<string | null> {
    const cheap = getCheapProvider(this.getConfig());
    if (!cheap) { return null; }

    try {
      const studentRaw = JSON.parse(fs.readFileSync(notebookUri.fsPath, 'utf-8'));
      const studentCells = studentRaw.cells || [];
      const markdownContent = studentCells
        .filter((c: any) => c.cell_type === 'markdown')
        .map((c: any) => Array.isArray(c.source) ? c.source.join('') : (c.source || ''))
        .join('\n\n---\n\n');

      // Pull TODO openings from the solution notebook so the summary can
      // describe what the student will build, not just the theory.
      const solutionDir = path.dirname(notebookUri.fsPath);
      const solutionPath = path.join(solutionDir, 'solution', filename);
      let solutionOverview = '';
      if (fs.existsSync(solutionPath)) {
        const solRaw = JSON.parse(fs.readFileSync(solutionPath, 'utf-8'));
        const todoCells = (solRaw.cells || [])
          .filter((c: any) => {
            if (c.cell_type !== 'code') { return false; }
            const src = Array.isArray(c.source) ? c.source.join('') : (c.source || '');
            return src.includes('TODO:');
          })
          .map((c: any) => {
            const src = Array.isArray(c.source) ? c.source.join('') : (c.source || '');
            return src.slice(0, 200);
          });
        if (todoCells.length > 0) {
          solutionOverview = `\n\nThe student will implement these exercises (showing first lines):\n${todoCells.join('\n---\n')}`;
        }
      }

      const prompt = `Summarize this Deep RL course notebook in 3-5 sentences. Cover: learning objectives, key concepts, what the student will build, and the progression from theory to code.\n\nNotebook content:\n${markdownContent.slice(0, 6000)}${solutionOverview}`;

      let result = '';
      await cheap.sendMessage(
        { staticPrefix: 'You are a concise technical summarizer. Reply with the summary only, no preamble.', dynamic: '' },
        [],
        prompt,
        (chunk) => { result += chunk; },
        () => {},
        () => {},
      );

      return result.trim() || null;
    } catch {
      return null;
    }
  }
}
